### PR TITLE
New Image slider on project page

### LINKED ISSUE #71: Design Change Requests/Fixes
- [x] Improve the Design of Project Images
Screen Shot 2020-08-17 at 9 52 54 AM
Sample is here - https://photos.app.goo.gl/7sQPgfU5NxGQUcWh8

- [x] Update Fonts for "project names" across the app

- [x] Reduce the padding at the bottom of Project Popup Card
Screen Shot 2020-08-17 at 10 25 44 AM

- [x] full address should appear (done in #76 )
Screen Shot 2020-08-17 at 10 39 01 AM

- [x] Flexbox to Currency Switcher

- [x] all projects should meet the bottom of screen

### PR DESCRIPTION
**Pull request by sarveshpro**
Fixes #71 Partially

Changes in this pull request:
-  Image Slider

### CODE REVIEW

**Comment by sarveshpro** [comment]
How does it look?

**Comment by sagararyal** [comment]
- [ ] Image is stuck loading on second image.

- [ ] Move indicator to bottom

- [ ] Show caption

- [ ] New issues for later [add full screen icon at top right]



Screen Shot 2020-08-19 at 4 27 19 PM

**Comment by sagararyal** [comment]
- [ ] Loading issue is still there.

Screen Shot 2020-08-20 at 11 57 24 AM

**Comment by sarveshpro** [comment]
Okay I'll check it again, @sagararyal @harshvitra do you think it is cache or something else? because the other day Harsh was not able to view it but it was working fine for me.

**Comment by sarveshpro** [comment]
things I need help with - 
SSR disabled for `react-insta-stories` module
setting PrimaryFontFamily to project images slider caption

**Pull request merged**
