### PR TITLE
tax deduction modal and countries implemented

### LINKED ISSUE #46: Tree Donatation Popup - Setting up the Tax deduction
### **Setting up the Tax deduction -** 

- [x] Get user's country from local storage, if this country exists in the taxDeduction countries array make this the `default country` or else use the `default country` mentioned there. 
- [x] When user switches the tax deduction on, hit the API with `default country` and get payment details  - HIT API
- [x] Open a popup. The popup should allow user to select the country - HIT API
- [x] Once the tax deduction switch is on, disable currency changes

### PR DESCRIPTION
**Pull request by nirali25parekh**
Fixes #46 

Changes in this pull request:
- the country obtained from local storage and tax deduction country displayed accordingly
- popup for tax deduction countries implemented
- enable and disable both the modals accordingly

@harshvitra

### CODE REVIEW

**Comment by sagararyal** [comment]
While tax country is identified based on location; currency is not being set properly.

  
Screen Shot 2020-08-11 at 11 50 14 AM

enabling tax deduction results to:

Screen Shot 2020-08-11 at 11 49 25 AM


DE --> Should convert the currency to EUR.

Since the  currency was redirected from EUR -> it should have already picked EUR on the first screen.

Also DE should be changed to `Germany`

**Comment by harshvitra** [comment]
@sagararyal 

Your suggested changes have been implemented 
Backend is not returning some data, have pushed the same query with the team

**Comment by harshvitra** [comment]
Fixes #43

**Comment by harshvitra** [comment]
Fixes #45

**Pull request merged**
